In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv("SriLanka_Weather_Dataset.csv")

In [4]:
df=dataset

In [5]:
#convert the time column in to datetime mode
df['time']=pd.to_datetime(df['time'])

In [6]:
#Create a new column named "Year"
df['year']=df['time'].dt.year

In [7]:
#Create a new column named "month"
df['month']=df['time'].dt.month

In [8]:
df

,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,sunset,...,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration,latitude,longitude,elevation,country,city,year,month
0,2010-01-01,2,30.0,22.7,26.1,34.4,25.2,29.2,2010-01-01T00:52,2010-01-01T12:35,...,27.4,20,4.58,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
1,2010-01-02,51,29.9,23.5,26.2,33.8,26.2,29.8,2010-01-02T00:52,2010-01-02T12:36,...,27.0,24,3.84,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
2,2010-01-03,51,29.5,23.2,26.0,34.3,26.3,29.9,2010-01-03T00:53,2010-01-03T12:36,...,27.4,16,3.65,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
3,2010-01-04,2,28.9,21.9,25.3,31.6,23.4,27.8,2010-01-04T00:53,2010-01-04T12:37,...,34.6,356,3.79,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
4,2010-01-05,1,28.1,21.3,24.5,30.1,23.1,26.1,2010-01-05T00:53,2010-01-05T12:37,...,37.1,355,4.97,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147475,2023-06-13,63,29.2,24.7,26.6,35.4,29.2,31.6,2023-06-13T00:24,2023-06-13T12:55,...,43.6,229,3.41,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147476,2023-06-14,61,29.1,25.4,26.9,34.3,30.4,32.0,2023-06-14T00:24,2023-06-14T12:55,...,40.0,224,3.00,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147477,2023-06-15,51,29.8,25.5,27.3,36.6,30.7,32.7,2023-06-15T00:24,2023-06-15T12:56,...,32.4,218,3.21,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147478,2023-06-16,53,30.5,25.5,27.7,36.2,30.1,32.4,2023-06-16T00:25,2023-06-16T12:56,...,41.8,236,3.97,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147479,2023-06-17,51,29.6,25.2,26.9,35.9,30.1,32.0,2023-06-17T00:25,2023-06-17T12:56,...,37.8,231,2.95,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6

In [9]:

# Check for 0 values in each column
zero_values = (df == 0).sum()

# Display the count of 0 values for each column
print(zero_values)

time                               0
weathercode                     1024
temperature_2m_max                 0
temperature_2m_min                 0
temperature_2m_mean                0
apparent_temperature_max           0
apparent_temperature_min           0
apparent_temperature_mean          0
sunrise                            0
sunset                             0
shortwave_radiation_sum            0
precipitation_sum              26727
rain_sum                       26727
snowfall_sum                  147480
precipitation_hours            26727
windspeed_10m_max                  0
windgusts_10m_max                  0
winddirection_10m_dominant       126
et0_fao_evapotranspiration         0
latitude                           0
longitude                          0
elevation                       9832
country                            0
city                               0
year                               0
month                              0
dtype: int64

In [10]:
# Replace 0 values with the mean of each numeric column
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].replace(0, df[numeric_cols].mean())

In [11]:
# Check for 0 values in each column
zero_values = (df == 0).sum()

# Display the count of 0 values for each column
print(zero_values)

time                               0
weathercode                        0
temperature_2m_max                 0
temperature_2m_min                 0
temperature_2m_mean                0
apparent_temperature_max           0
apparent_temperature_min           0
apparent_temperature_mean          0
sunrise                            0
sunset                             0
shortwave_radiation_sum            0
precipitation_sum                  0
rain_sum                           0
snowfall_sum                  147480
precipitation_hours                0
windspeed_10m_max                  0
windgusts_10m_max                  0
winddirection_10m_dominant         0
et0_fao_evapotranspiration         0
latitude                           0
longitude                          0
elevation                          0
country                            0
city                               0
year                               0
month                              0
dtype: int64

In [12]:
print(df)

             time  weathercode  temperature_2m_max  temperature_2m_min  \
0      2010-01-01          2.0                30.0                22.7
1      2010-01-02         51.0                29.9                23.5
2      2010-01-03         51.0                29.5                23.2
3      2010-01-04          2.0                28.9                21.9
4      2010-01-05          1.0                28.1                21.3
...           ...          ...                 ...                 ...
147475 2023-06-13         63.0                29.2                24.7
147476 2023-06-14         61.0                29.1                25.4
147477 2023-06-15         51.0                29.8                25.5
147478 2023-06-16         53.0                30.5                25.5
147479 2023-06-17         51.0                29.6                25.2

        temperature_2m_mean  apparent_temperature_max  \
0                      26.1                      34.4
1                      26.2                      33.8
2                      26.0                      34.3
3                      25.3                      31.6
4                      24.5                      30.1
...                     ...                       ...
147475                 26.6                      35.4
147476                 26.9                      34.3
147477                 27.3                      36.6
147478                 27.7                      36.2
147479                 26.9                      35.9

        apparent_temperature_min  apparent_temperature_mean           sunrise  \
0                           25.2                       29.2  2010-01-01T00:52
1                           26.2                       29.8  2010-01-02T00:52
2                           26.3                       29.9  2010-01-03T00:53
3                           23.4                       27.8  2010-01-04T00:53
4                           23.1                       26.1  2010-01-05T00:53
...                          ...                        ...               ...
147475                      29.2                       31.6  2023-06-13T00:24
147476                      30.4                       32.0  2023-06-14T00:24
147477                      30.7                       32.7  2023-06-15T00:24
147478                      30.1                       32.4  2023-06-16T00:25
147479                      30.1                       32.0  2023-06-17T00:25

                  sunset  ...  windgusts_10m_max  winddirection_10m_dominant  \
0       2010-01-01T12:35  ...               27.4                        20.0
1       2010-01-02T12:36  ...               27.0                        24.0
2       2010-01-03T12:36  ...               27.4                        16.0
3       2010-01-04T12:37  ...               34.6                       356.0
4       2010-01-05T12:37  ...               37.1                       355.0
...                  ...  ...                ...                         ...
147475  2023-06-13T12:55  ...               43.6                       229.0
147476  2023-06-14T12:55  ...               40.0                       224.0
147477  2023-06-15T12:56  ...               32.4                       218.0
147478  2023-06-16T12:56  ...               41.8                       236.0
147479  2023-06-17T12:56  ...               37.8                       231.0

        et0_fao_evapotranspiration  latitude  longitude  elevation    country  \
0                             4.58  7.000000  79.899994       16.0  Sri Lanka
1                             3.84  7.000000  79.899994       16.0  Sri Lanka
2                             3.65  7.000000  79.899994       16.0  Sri Lanka
3                             3.79  7.000000  79.899994       16.0  Sri Lanka
4                             4.97  7.000000  79.899994       16.0  Sri Lanka
...                            ...       ...        ...        ...        ...
147475                        3.41  6.900002  80.000000       20.0  Sri Lanka
147476                        3.00  6.900002  80.000000       20.0  Sri Lanka
147477                        3.21  6.900002  80.000000       20.0  Sri Lanka
147478                        3.97  6.900002  80.000000       20.0  Sri Lanka
147479                        2.95  6.900002  80.000000       20.0  Sri Lanka

           city  year  month
0       Colombo  2010      1
1       Colombo  2010      1
2       Colombo  2010      1
3       Colombo  2010      1
4       Colombo  2010      1
...         ...   ...    ...
147475  Oruwala  2023      6
147476  Oruwala  2023      6
147477  Oruwala  2023      6
147478  Oruwala  2023      6
147479  Oruwala  2023      6

[147480 rows x 26 columns]

In [13]:
# Select columns for which you want to detect and remove outliers
columns_of_interest = ['shortwave_radiation_sum', 'rain_sum']

# Calculate the first quartile (Q1) and third quartile (Q3) for the columns of interest
Q1 = df[columns_of_interest].quantile(0.25)
Q3 = df[columns_of_interest].quantile(0.75)

# Calculate the IQR for each column
IQR = Q3 - Q1

# Define a threshold for considering values as outliers (e.g., 1.5 times IQR)
threshold = 1.5

# Create a boolean mask for outliers
outliers_mask = ((df[columns_of_interest] < (Q1 - threshold * IQR)) |
                 (df[columns_of_interest] > (Q3 + threshold * IQR))).any(axis=1)

# Count 0 values in the outliers for the columns of interest
zero_values = (df[columns_of_interest][outliers_mask] == 0).sum()

# Display the count of 0 values for each column
print(zero_values)

shortwave_radiation_sum    0
rain_sum                   0
dtype: int64

In [14]:
# Select columns for which you want to detect and remove outliers
columns_of_interest = ['shortwave_radiation_sum', 'rain_sum','temperature_2m_max','temperature_2m_min','temperature_2m_mean','apparent_temperature_max','apparent_temperature_min',
'apparent_temperature_mean','shortwave_radiation_sum','precipitation_sum','rain_sum','precipitation_hours','windspeed_10m_max','windgusts_10m_max','winddirection_10m_dominant','et0_fao_evapotranspiration',
'latitude','longitude','elevation']

# Calculate the first quartile (Q1) and third quartile (Q3) for each column
Q1 = df[columns_of_interest].quantile(0.25)
Q3 = df[columns_of_interest].quantile(0.75)

# Calculate the IQR for each column
IQR = Q3 - Q1

# Define a threshold for considering values as outliers (e.g., 1.5 times IQR)
threshold = 1.5

# Create a boolean mask for outliers
outliers_mask = ((df[columns_of_interest] < (Q1 - threshold * IQR)) |
                 (df[columns_of_interest] > (Q3 + threshold * IQR))).any(axis=1)

# Remove rows with outliers
weather_no_outliers = df[~outliers_mask]

In [15]:
weather_no_outliers

,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,sunset,...,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration,latitude,longitude,elevation,country,city,year,month
0,2010-01-01,2.0,30.0,22.7,26.1,34.4,25.2,29.2,2010-01-01T00:52,2010-01-01T12:35,...,27.4,20.0,4.58,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
1,2010-01-02,51.0,29.9,23.5,26.2,33.8,26.2,29.8,2010-01-02T00:52,2010-01-02T12:36,...,27.0,24.0,3.84,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
2,2010-01-03,51.0,29.5,23.2,26.0,34.3,26.3,29.9,2010-01-03T00:53,2010-01-03T12:36,...,27.4,16.0,3.65,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
3,2010-01-04,2.0,28.9,21.9,25.3,31.6,23.4,27.8,2010-01-04T00:53,2010-01-04T12:37,...,34.6,356.0,3.79,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
4,2010-01-05,1.0,28.1,21.3,24.5,30.1,23.1,26.1,2010-01-05T00:53,2010-01-05T12:37,...,37.1,355.0,4.97,7.000000,79.899994,16.0,Sri Lanka,Colombo,2010,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147473,2023-06-11,61.0,28.8,25.2,26.9,35.1,30.4,32.2,2023-06-11T00:24,2023-06-11T12:55,...,37.8,226.0,2.99,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147476,2023-06-14,61.0,29.1,25.4,26.9,34.3,30.4,32.0,2023-06-14T00:24,2023-06-14T12:55,...,40.0,224.0,3.00,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147477,2023-06-15,51.0,29.8,25.5,27.3,36.6,30.7,32.7,2023-06-15T00:24,2023-06-15T12:56,...,32.4,218.0,3.21,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147478,2023-06-16,53.0,30.5,25.5,27.7,36.2,30.1,32.4,2023-06-16T00:25,2023-06-16T12:56,...,41.8,236.0,3.97,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6
147479,2023-06-17,51.0,29.6,25.2,26.9,35.9,30.1,32.0,2023-06-17T00:25,2023-06-17T12:56,...,37.8,231.0,2.95,6.900002,80.000000,20.0,Sri Lanka,Oruwala,2023,6

In [16]:
# Ensure weather_no_outliers is a copy of the original DataFrame, not a view
weather_no_outliers = weather_no_outliers.copy()

# List of columns to drop
columns_to_drop = ['time', 'sunrise', 'rain_sum', 'sunset', 'snowfall_sum', 'country', 'city']

# Check which columns are available in the DataFrame
columns_available_to_drop = [col for col in columns_to_drop if col in weather_no_outliers.columns]

# Drop the available columns
weather_no_outliers.drop(columns=columns_available_to_drop, inplace=True)

# Display remaining columns
print(weather_no_outliers.columns)

Index(['weathercode', 'temperature_2m_max', 'temperature_2m_min',
       'temperature_2m_mean', 'apparent_temperature_max',
       'apparent_temperature_min', 'apparent_temperature_mean',
       'shortwave_radiation_sum', 'precipitation_sum', 'precipitation_hours',
       'windspeed_10m_max', 'windgusts_10m_max', 'winddirection_10m_dominant',
       'et0_fao_evapotranspiration', 'latitude', 'longitude', 'elevation',
       'year', 'month'],
      dtype='object')

In [17]:
weather_no_outliers

,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,shortwave_radiation_sum,precipitation_sum,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration,latitude,longitude,elevation,year,month
0,2.0,30.0,22.7,26.1,34.4,25.2,29.2,20.92,5.975637,8.762524,11.7,27.4,20.0,4.58,7.000000,79.899994,16.0,2010,1
1,51.0,29.9,23.5,26.2,33.8,26.2,29.8,17.71,0.100000,1.000000,13.0,27.0,24.0,3.84,7.000000,79.899994,16.0,2010,1
2,51.0,29.5,23.2,26.0,34.3,26.3,29.9,17.76,0.600000,3.000000,12.3,27.4,16.0,3.65,7.000000,79.899994,16.0,2010,1
3,2.0,28.9,21.9,25.3,31.6,23.4,27.8,16.50,5.975637,8.762524,17.0,34.6,356.0,3.79,7.000000,79.899994,16.0,2010,1
4,1.0,28.1,21.3,24.5,30.1,23.1,26.1,23.61,5.975637,8.762524,18.7,37.1,355.0,4.97,7.000000,79.899994,16.0,2010,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147473,61.0,28.8,25.2,26.9,35.1,30.4,32.2,14.88,4.900000,18.000000,13.6,37.8,226.0,2.99,6.900002,80.000000,20.0,2023,6
147476,61.0,29.1,25.4,26.9,34.3,30.4,32.0,14.97,7.300000,19.000000,16.4,40.0,224.0,3.00,6.900002,80.000000,20.0,2023,6
147477,51.0,29.8,25.5,27.3,36.6,30.7,32.7,15.89,3.200000,17.000000,12.6,32.4,218.0,3.21,6.900002,80.000000,20.0,2023,6
147478,53.0,30.5,25.5,27.7,36.2,30.1,32.4,19.21,5.600000,24.000000,20.5,41.8,236.0,3.97,6.900002,80.000000,20.0,2023,6
147479,51.0,29.6,25.2,26.9,35.9,30.1,32.0,14.80,5.000000,23.000000,16.3,37.8,231.0,2.95,6.900002,80.000000,20.0,2023,6

In [18]:
# Drop the  weathercode column
weather_no_outliers.drop(columns='weathercode', inplace=True)

In [19]:
#download the dataset
weather_no_outliers.to_csv("IT21308598_preprocessed_weather.csv", index=False)